add_test([=[Cell.PutRoundTrip]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.PutRoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.PutRoundTrip]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.Tombstone]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.Tombstone]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.Tombstone]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.EmptyValuePut]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.EmptyValuePut]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.EmptyValuePut]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.SlotBoundaries]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.SlotBoundaries]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.SlotBoundaries]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.BinaryValueWithNuls]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.BinaryValueWithNuls]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.BinaryValueWithNuls]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.ReservedBitsIgnoredForTombstone]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.ReservedBitsIgnoredForTombstone]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.ReservedBitsIgnoredForTombstone]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cell.HighestSlotWins]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Cell.HighestSlotWins]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cell.HighestSlotWins]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.RetireFreesWhenNoGuard]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.RetireFreesWhenNoGuard]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.RetireFreesWhenNoGuard]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.GuardDelaysReclamation]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.GuardDelaysReclamation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.GuardDelaysReclamation]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.NewGuardAfterRetireDoesNotBlock]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.NewGuardAfterRetireDoesNotBlock]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.NewGuardAfterRetireDoesNotBlock]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.MultipleGuardsHoldUntilAllExit]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.MultipleGuardsHoldUntilAllExit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.MultipleGuardsHoldUntilAllExit]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.DestructorFreesPending]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.DestructorFreesPending]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.DestructorFreesPending]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Epoch.ConcurrentReadersAndRetire]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Epoch.ConcurrentReadersAndRetire]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Epoch.ConcurrentReadersAndRetire]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InnerPage.ChildIndexFor]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=InnerPage.ChildIndexFor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InnerPage.ChildIndexFor]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Descent.SingleLeafRoot]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Descent.SingleLeafRoot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Descent.SingleLeafRoot]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Descent.TwoLevelTree]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Descent.TwoLevelTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Descent.TwoLevelTree]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Descent.ThreeLevelTree]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Descent.ThreeLevelTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Descent.ThreeLevelTree]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Descent.EmptyRoot]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Descent.EmptyRoot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Descent.EmptyRoot]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.BuildAndFind]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.BuildAndFind]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.BuildAndFind]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.LookupDecodesCell]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.LookupDecodesCell]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.LookupDecodesCell]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.Tombstone]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.Tombstone]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.Tombstone]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.OrderedIterationAndBoundaries]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.OrderedIterationAndBoundaries]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.OrderedIterationAndBoundaries]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.LowerBound]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.LowerBound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.LowerBound]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.RightSibling]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.RightSibling]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.RightSibling]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.BloomTrueNegativeAndFpRate]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.BloomTrueNegativeAndFpRate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.BloomTrueNegativeAndFpRate]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LeafPage.DataBytesNonZero]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=LeafPage.DataBytesNonZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LeafPage.DataBytesNonZero]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MappingTable.AllocStoreGet]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=MappingTable.AllocStoreGet]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MappingTable.AllocStoreGet]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MappingTable.InvalidPid]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=MappingTable.InvalidPid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MappingTable.InvalidPid]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MappingTable.FreeAndRecycle]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=MappingTable.FreeAndRecycle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MappingTable.FreeAndRecycle]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MappingTable.SegmentGrowth]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=MappingTable.SegmentGrowth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MappingTable.SegmentGrowth]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MappingTable.ConcurrentReadersSingleWriter]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=MappingTable.ConcurrentReadersSingleWriter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MappingTable.ConcurrentReadersSingleWriter]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Slice.BasicAndCompare]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Slice.BasicAndCompare]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Slice.BasicAndCompare]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Slice.EmptyAndBinary]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Slice.EmptyAndBinary]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Slice.EmptyAndBinary]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Status.Codes]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Status.Codes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Status.Codes]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Options.Defaults]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Options.Defaults]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Options.Defaults]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Env.DefaultSingleton]=]  /cjdata/cpp/crowkv/crowtree/build-tsan/crowtree_tests [==[--gtest_filter=Env.DefaultSingleton]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Env.DefaultSingleton]=]  PROPERTIES WORKING_DIRECTORY /cjdata/cpp/crowkv/crowtree/build-tsan SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  crowtree_tests_TESTS Cell.PutRoundTrip Cell.Tombstone Cell.EmptyValuePut Cell.SlotBoundaries Cell.BinaryValueWithNuls Cell.ReservedBitsIgnoredForTombstone Cell.HighestSlotWins Epoch.RetireFreesWhenNoGuard Epoch.GuardDelaysReclamation Epoch.NewGuardAfterRetireDoesNotBlock Epoch.MultipleGuardsHoldUntilAllExit Epoch.DestructorFreesPending Epoch.ConcurrentReadersAndRetire InnerPage.ChildIndexFor Descent.SingleLeafRoot Descent.TwoLevelTree Descent.ThreeLevelTree Descent.EmptyRoot LeafPage.BuildAndFind LeafPage.LookupDecodesCell LeafPage.Tombstone LeafPage.OrderedIterationAndBoundaries LeafPage.LowerBound LeafPage.RightSibling LeafPage.BloomTrueNegativeAndFpRate LeafPage.DataBytesNonZero MappingTable.AllocStoreGet MappingTable.InvalidPid MappingTable.FreeAndRecycle MappingTable.SegmentGrowth MappingTable.ConcurrentReadersSingleWriter Slice.BasicAndCompare Slice.EmptyAndBinary Status.Codes Options.Defaults Env.DefaultSingleton)
