// Copyright 2026-present buzzcrow <buzzcrow@126.com>
// Licensed under the Apache License, Version 2.0.

fn main() {
    let proto_dir = "src/proto";

    // chunkdb_type.proto is currently empty (ChunkId moved to
    // common_type.proto) but kept for future chunkdb types.
    let protos = [
        "src/proto/common_type.proto",
        "src/proto/diskdb_type.proto",
        "src/proto/diskdb_op.proto",
        "src/proto/diskdb_sys_op.proto",
        "src/proto/diskdb_service.proto",
        "src/proto/diskdb_sys_service.proto",
    ];

    tonic_build::configure()
        .type_attribute(".", "#[allow(clippy::must_use_candidate)]")
        // Add serde + Eq + Hash to message types that internal Rust
        // types embed (for bincode/JSON serialization of records and
        // group-0 sysdata). Debug is already generated by prost::Message.
        .type_attribute(
            "DiskId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "ChunkId",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "Segment",
            "#[derive(Eq, Hash, serde::Serialize, serde::Deserialize)]",
        )
        // Value types (serde for bincode/JSON storage).
        .type_attribute("ZoneValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "BusyBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "FreeBlockValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("DiskValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "DiskGroupValue",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        // Query response types (key + value fields flattened).
        .type_attribute("DiskInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskGroupInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Common sysdata value types (serde for bincode/JSON storage).
        .type_attribute("RackValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("NodeValue", "#[derive(serde::Serialize, serde::Deserialize)]")
        // Enums.
        .type_attribute("HwStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("DiskType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "ZoneAllocationState",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .compile_protos(&protos, &[proto_dir])
        .expect("failed to compile diskdb protos");
}
